name: Validate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'typedoc.json'
      - '.github/workflows/docs.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Generate and check documentation
        run: |
          yarn docs
          if [ -n "$(git status --porcelain docs/)" ]; then
            echo "⚠️ Documentation is out of sync with source code"
            echo "Please run 'yarn docs' locally and commit the changes"
            exit 1
          fi